sudo: required
language: go

dist: bionic

go:
- "1.13"

services:
- docker

before_script:
  - ./hack/install-docker.sh
  - ./hack/install-buildx.sh

script:
- docker buildx version
- TAG=${TRAVIS_TAG:=latest} make docker-build

before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: TAG=${TRAVIS_TAG} make docker-publish
  on:
    tags: true
