apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    verbs:
      - get
      - create
      - update
      - patch
    resources:
      - leases
