apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: registry-creds-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-creds-controller
  namespace: system
  labels:
    control-plane: registry-creds-controller
spec:
  selector:
    matchLabels:
      control-plane: registry-creds-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-creds-controller
    spec:
      containers:
      - command:
        - /controller
        args:
        - --enable-leader-election
        image: ghcr.io/alexellis/registry-creds:0.3.1
        name: controller
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 45Mi
      terminationGracePeriodSeconds: 10
