name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Local build
        id: local_build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            Version=dev
            GitCommit=${{ github.sha }}
          outputs: "type=docker,push=false"
          platforms: linux/amd64
          tags: ghcr.io/alexellis/registry-creds:${{ github.sha }}

      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.6.2
        with:
          # This is the KinD version, not the Kubernetes version
          version: "v0.25.0"

      - name: Load test image
        run: kind load --loglevel trace docker-image ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Apply manifests
        run: |
          TAG=${{ github.sha }} make shrinkwrap
          cat ./manifest.yaml | grep ghcr
          kubectl apply -f ./manifest.yaml

      - name: Check deployment
        run:
          kubectl rollout status -n registry-creds-system deploy/registry-creds-registry-creds-controller --timeout=2m || kubectl describe -n registry-creds-system deploy/registry-creds-registry-creds-controller && kubectl get events -n registry-creds-system
